[package]
name = "rustbert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]  # or ["rlib"] for a static library

[dependencies]
tokenizers = "0.13.3"
libc = "0.2.112"